#pragma once
#include<string>
#include<vector>
using namespace std;



//This is a struct and a class that stores details of a books when a user have searched book.

struct book
{
	//There are details of a book
	string title;
	string author;
	string rackNo;
	string publisher;
	string subject;
	string titleId;
	float compare_count;	//This count is generated by compare function which compares the current book data and search query.
};


//This is actual class that stores details of all books that are found appropriate for search query.
//The actual functions are present in bookClass.cpp

public class bookClass
{
	vector<book> v;

public:
	bookClass(void);
	void insert(string title,string author,string rackNo,string publisher,string subject ,string titleId, float compare_count);
	int count();
	string Title(int i);
	string Author(int i);
	string RackNo(int i);
	string Subject(int i);
	string Publisher(int i);
	string TitleId(int i);
	void sort();
	void clear();
};

